language: node_js
node_js:
  - "8"

cache:
  directories:
    - $HOME/.npm
    - node_modules

install:
  - npm prune
  - npm install

script:
  - npm run lint
  # Both test & coverage.
  - npm run travis

# Allow Travis tests to run in containers.
sudo: false
